apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-indexing-service
  labels:
    app: word-indexing-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: word-indexing-service
  template:
    metadata:
      labels:
        app: word-indexing-service
    spec:
      containers:
        - name: word-indexing-service
          image: your-dockerhub-username/word-indexing-app:1.0  # Replace with your registry path
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: word-indexing-service
spec:
  selector:
    app: word-indexing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP